hamiltonian:
  type: heisenberg      # Type of Hamiltonian
  params:
    L: 8                # 系统大小(Lx = Ly)
    dim: 2             # Dimension of the system
    J: 1.0             # The coupling constant
    pbc: True          # Whether the system has periodic boundary conditions
    Sz_total: 0        # Total spin in z direction

model_params:
  modes1: 8           # Number of modes in the Fourier basis (x direction) Number of modes should be less than or equal to Lx and Ly
  modes2: 5           # Number of modes in the Fourier basis (y direction)
  width: 16            # Number of channels in the hidden layers

vmc:
  n_samples: 8192 #1000      # Number of samples for VMC
  lr: 1e-3             # Learning rate for the optimizer
  sr: True            # Whether to use stochastic reconfiguration
  n_iter: 2000          # Number of iterations for VMC
  init_state: random   # Initial state for the wave function, can be 'random' or 'ground_state'
