hamiltonian:
  type: heisenberg      # 注意小写，与代码一致
  params:
    Lx: 4              # x方向格点数（你可以改成你需要的大小）
    Ly: 4              # y方向格点数
    dim: 2             # 二维系统
    J: 1.0             # 耦合常数
    pbc: True          # 是否周期边界
    Sz_total: 0        # 总磁量子数（如无需求可不写）

model_params:
  modes1: 3           # FNO 的 Fourier 模式数（x方向）
  modes2: 3           # FNO 的 Fourier 模式数（y方向）Number of modes should be less than or equal to Lx and Ly
  width: 16            # FNO 网络通道数

vmc:
  n_samples: 128 #1000      # Monte Carlo 采样数
  lr: 1e-3             # 学习率
  n_iter: 500          # 迭代次数
  init_state: random   # 初始自旋配置，可选 random 或 updown
